[build]
cmake.minimum-version = "3.23"

cmake.args = [
  "-DCMAKE_TOOLCHAIN_FILE=$VCPKG_TOOLCHAIN_FILE",
  "-DVCPKG_TARGET_TRIPLET=$VCPKG_TARGET_TRIPLET",
  "-DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH",
  "-DCELUX_BUILD_PYTHON=ON",
]
